services:
  - type: web
    name: privacy-cover-bot
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python privacy_cover_bot.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SEND_DELAY
        value: "1.9"
      - key: ALBUM_FLUSH_TIMEOUT
        value: "500"
      - key: MAX_QUEUE_SIZE
        value: "6000"
      - key: NEAR_DUP_THRESHOLD
        value: "6"
